#!/usr/bin/env python3
import sys
import os

from analyzer import Analyzer
from termcolor import colored
from helpers import get_user_timeline

# TODO
def main():
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @screen_name")
        
    # if it returns None, exit the program and return '3'   
    if get_user_timeline(sys.argv[1]) != None:
        
        # make variables 'tweets', 'positives' and 'negatives'
        tweets = get_user_timeline(sys.argv[1])
        positives = os.path.join(sys.path[0], "positive-words.txt")
        negatives = os.path.join(sys.path[0], "negative-words.txt")
        
        # instantiate analyzer
        analyzer = Analyzer(positives, negatives)
        
        # check for the last 50 tweets if they're positive, negative or neutral
        for i in range(50):
            # analyze word
            score = analyzer.analyze(tweets[i])
            
            if score > 0.0:
                print(colored("{} {}", "green").format(score, tweets[i]))
            elif score < 0.0:
                print(colored("{} {}", "red").format(score, tweets[i]))
            else:
                print(colored("{} {}", "yellow").format(score, tweets[i]))
    else:
        sys.exit(3)
    
if __name__ == "__main__":
    main()
